import type { EcosystemProject } from "@/domain/types";

/**
 * Seed ecosystem projects representing Unicity Sphere-connected applications.
 * Health engine mutates live copies each tick.
 */
export function createSeedProjects(now = new Date().toISOString()): EcosystemProject[] {
  return [
    {
      id: "proj_sphere_market",
      name: "Sphere Market API",
      slug: "sphere-market",
      url: "https://market-api.unicity.network",
      status: "healthy",
      apiLatencyMs: 120,
      storageUtilizationPct: 42,
      responseTimeMs: 180,
      uptimePct: 99.95,
      failureRatePct: 0.2,
      txFailureRatePct: 0.1,
      messagingFailureRatePct: 0.15,
      paymentFailureRatePct: 0.05,
      activeUsers: 420,
      activeAgents: 86,
      lastCheckedAt: now,
      tags: ["marketplace", "intents", "core"],
    },
    {
      id: "proj_wallet_api",
      name: "Wallet API Gateway",
      slug: "wallet-api",
      url: "https://wallet-api.unicity.network",
      status: "healthy",
      apiLatencyMs: 95,
      storageUtilizationPct: 55,
      responseTimeMs: 140,
      uptimePct: 99.98,
      failureRatePct: 0.12,
      txFailureRatePct: 0.08,
      messagingFailureRatePct: 0.1,
      paymentFailureRatePct: 0.2,
      activeUsers: 1200,
      activeAgents: 210,
      lastCheckedAt: now,
      tags: ["payments", "delivery", "core"],
    },
    {
      id: "proj_nostr_relay",
      name: "Nostr Relay Mesh",
      slug: "nostr-relay",
      url: "wss://nostr-relay.testnet.unicity.network",
      status: "healthy",
      apiLatencyMs: 60,
      storageUtilizationPct: 38,
      responseTimeMs: 75,
      uptimePct: 99.9,
      failureRatePct: 0.3,
      txFailureRatePct: 0,
      messagingFailureRatePct: 0.4,
      paymentFailureRatePct: 0,
      activeUsers: 890,
      activeAgents: 340,
      lastCheckedAt: now,
      tags: ["messaging", "identity"],
    },
    {
      id: "proj_agent_hosting",
      name: "Agent Hosting Cluster",
      slug: "agent-hosting",
      status: "healthy",
      apiLatencyMs: 210,
      storageUtilizationPct: 67,
      responseTimeMs: 280,
      uptimePct: 99.7,
      failureRatePct: 0.8,
      txFailureRatePct: 0.3,
      messagingFailureRatePct: 0.5,
      paymentFailureRatePct: 0.2,
      activeUsers: 160,
      activeAgents: 520,
      lastCheckedAt: now,
      tags: ["agents", "compute"],
    },
    {
      id: "proj_token_engine",
      name: "Token Engine Gateway",
      slug: "token-engine",
      url: "https://gateway.testnet2.unicity.network",
      status: "healthy",
      apiLatencyMs: 150,
      storageUtilizationPct: 48,
      responseTimeMs: 200,
      uptimePct: 99.92,
      failureRatePct: 0.25,
      txFailureRatePct: 0.4,
      messagingFailureRatePct: 0,
      paymentFailureRatePct: 0.35,
      activeUsers: 980,
      activeAgents: 150,
      lastCheckedAt: now,
      tags: ["settlement", "tokens", "core"],
    },
    {
      id: "proj_sphere_dash",
      name: "Sphere Dashboard",
      slug: "sphere-dashboard",
      url: "https://sphere.unicity.network",
      status: "healthy",
      apiLatencyMs: 180,
      storageUtilizationPct: 33,
      responseTimeMs: 240,
      uptimePct: 99.85,
      failureRatePct: 0.5,
      txFailureRatePct: 0.1,
      messagingFailureRatePct: 0.2,
      paymentFailureRatePct: 0.1,
      activeUsers: 2400,
      activeAgents: 45,
      lastCheckedAt: now,
      tags: ["frontend", "ux"],
    },
  ];
}
